# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_factors', '0005_auto_20160719_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandoption',
            name='requisites',
            field=models.ManyToManyField(to='bike_factors.BikeOption', verbose_name='Bike types that this feature is available for'),
        ),
        migrations.AlterField(
            model_name='cosmeticoption',
            name='requisites',
            field=models.ManyToManyField(to='bike_factors.BikeOption', verbose_name='Bike types that this feature is available for'),
        ),
        migrations.AlterField(
            model_name='featuresoption',
            name='requisites',
            field=models.ManyToManyField(to='bike_factors.BikeOption', verbose_name='Bike types that this feature is available for'),
        ),
        migrations.AlterField(
            model_name='frameoption',
            name='requisites',
            field=models.ManyToManyField(to='bike_factors.BikeOption', verbose_name='Bike types that this feature is available for'),
        ),
    ]
