# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory', '0003_auto_20160721_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsku',
            name='customSku',
            field=models.CharField(max_length=12),
        ),
    ]
